### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by lukeburns** [ripple/ripple-wallet#4]
Can someone update `ripple-wallet` on npm? It was last published a year ago, and usage of the library has changed from

``` javascript
var RippleWallet = require('ripple-wallet');
var wallet = RippleWallet.generate()
```

to

``` javascript
var RippleWallet = require('ripple-wallet')({ sjcl: require("ripple-lib").sjcl });
var wallet = RippleWallet.generate()
```

**Comment by clark800** [comment]
This repo is for the npm package `ripple-wallet-generator`. `ripple-wallet` is not owned by our organization.

**Comment by lukeburns** [comment]
Isn't it owned by @stevenzeiler, who works for Ripple and also contributes to this repo? 

Whatever the case, it'd be helpful if that information available in the README.

**Comment by clark800** [comment]
> Isn't it owned by @stevenzeiler, who works for Ripple and also contributes to this repo?

Yes. 

> Whatever the case, it'd be helpful if that information available in the README.

It doesn't really make sense to document unrelated npm packages since anyone can publish npm packages that contain the word "ripple". The npm website links to this repo and the package.json shows the npm package name.
